openapi: 3.0.0
info:
  title: StudentPals
  description: IGP Group 17 Internal API Documentation
  version: 0.0.1

servers:
  - url: http://student-pals.com/api/v1
    description: Main (production) entrypoint.

paths:
  /students/{id}:
    get:
      summary: Returns a specific user by ID.
      parameters:
        - name: id
        in: path
        required: true
        description: The ID of the student.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: OK (A JSON schema for the student)
          content:
            application/json:
              schema:
                type: object
                properties:
                  name: string
                  format: int64
                  example: "John Benardis"
