openapi: 3.0.0
info:
  title: StudentPals
  description: IGP Group 17 Internal API Documentation
  version: 0.0.1

servers:
  - url: http://student-pals.com/api/v1
    description: Main (production) entrypoint.

paths:
  /students/{id}:
    get:
      summary: /students/{id}
      description: Returns a specific user by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the student.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK (A JSON schema for the student)
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "John Benardis"
        '400':
          description: The specified student ID is invalid (not a number)
        '404':
          description: A user with the specified ID was not found
        default:
          description: Unexpected error
