name: Aggregate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copycat Action
        uses: andstor/copycat-action@v3.2.3
        with:
          personal_token: ${{ secrets.AGGREGATED_SOURCE_TOKEN }}
          src_path: /.
          dst_path: /docs/
          dst_owner: IGPGroup17
          dst_repo_name: studentpals-aggregated-source
          src_branch: master
          dst_branch: master
          commit_message: From documentation. 
